-- 迁移：users 表重命名为 admin_users，并新增权限相关表
-- 注意：已有 users 表数据会保留

-- 1. 重命名 users 表
ALTER TABLE users RENAME TO admin_users;

-- 2. 同步重命名约束名（PostgreSQL 约束名不随表名自动变）
ALTER TABLE admin_users RENAME CONSTRAINT uk_users_uid      TO uk_admin_users_uid;
ALTER TABLE admin_users RENAME CONSTRAINT uk_users_username TO uk_admin_users_username;

-- 3. 删除 admin_users 表中与管理员无关的字段（2FA 是管理员功能，暂留）
--    phone / avatar 对管理员意义不大，保留 email 用于通知
--    如不需要可以后续再建迁移删除，此处不做破坏性变更

-- 4. 角色表
CREATE TABLE IF NOT EXISTS roles (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64)  NOT NULL,
    title       VARCHAR(64)  NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',
    status      SMALLINT     NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_roles_name UNIQUE (name)
);

-- 5. 菜单与按钮权限表
CREATE TABLE IF NOT EXISTS menus (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  BIGINT       NOT NULL DEFAULT 0,
    name       VARCHAR(128) NOT NULL,
    title      VARCHAR(64)  NOT NULL,
    type       SMALLINT     NOT NULL DEFAULT 1,  -- 1=菜单 2=按钮
    icon       VARCHAR(64)  NOT NULL DEFAULT '',
    sort       INT          NOT NULL DEFAULT 0,
    status     SMALLINT     NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_menus_name UNIQUE (name)
);

-- 6. 角色-权限关联表
CREATE TABLE IF NOT EXISTS role_menus (
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    menu_id BIGINT NOT NULL REFERENCES menus(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, menu_id)
);

-- 7. 管理员-角色关联表
CREATE TABLE IF NOT EXISTS admin_user_roles (
    admin_user_id BIGINT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
    role_id       BIGINT NOT NULL REFERENCES roles(id)       ON DELETE CASCADE,
    PRIMARY KEY (admin_user_id, role_id)
);

-- 8. updated_at 触发器（复用已有函数 set_updated_at）
DROP TRIGGER IF EXISTS trg_roles_updated_at ON roles;
CREATE TRIGGER trg_roles_updated_at
    BEFORE UPDATE ON roles
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_menus_updated_at ON menus;
CREATE TRIGGER trg_menus_updated_at
    BEFORE UPDATE ON menus
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 9. 索引
CREATE INDEX IF NOT EXISTS idx_menus_parent_id ON menus(parent_id);
CREATE INDEX IF NOT EXISTS idx_role_menus_role_id ON role_menus(role_id);
CREATE INDEX IF NOT EXISTS idx_admin_user_roles_user_id ON admin_user_roles(admin_user_id);
