-- 操作日志表：记录所有鉴权接口的请求/响应信息，供审计和问题排查使用
CREATE TABLE IF NOT EXISTS operation_logs (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    op_account   VARCHAR(64)  NOT NULL DEFAULT '',
    op_time      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    ip           VARCHAR(64)  NOT NULL DEFAULT '',
    req_func     VARCHAR(128) NOT NULL DEFAULT '',
    req_url      VARCHAR(512) NOT NULL DEFAULT '',
    req_data     TEXT         NOT NULL DEFAULT '',
    resp_data    TEXT         NOT NULL DEFAULT '',
    req_method   VARCHAR(16)  NOT NULL DEFAULT '',
    elapsed_time BIGINT       NOT NULL DEFAULT 0,  -- 毫秒
    occur_err    BOOLEAN      NOT NULL DEFAULT FALSE,
    err_msg      TEXT         NOT NULL DEFAULT '',
    success      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_operation_logs_op_account ON operation_logs(op_account);
CREATE INDEX IF NOT EXISTS idx_operation_logs_op_time    ON operation_logs(op_time DESC);
