/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const COMMA_NUMBERS: typeof import('./utils/constant').COMMA_NUMBERS
  const DECIMAL_SIX: typeof import('./utils/constant').DECIMAL_SIX
  const DECIMAL_TWO: typeof import('./utils/constant').DECIMAL_TWO
  const EMAIL: typeof import('./utils/constant').EMAIL
  const EffectScope: typeof import('vue').EffectScope
  const GREATER_THAN_ZERO_NUMBER: typeof import('./utils/constant').GREATER_THAN_ZERO_NUMBER
  const INTER_NUMBER: typeof import('./utils/constant').INTER_NUMBER
  const IP_V4: typeof import('./utils/constant').IP_V4
  const IP_V6: typeof import('./utils/constant').IP_V6
  const Index: typeof import('./store/Index').default
  const NINETEEN_DIGITS: typeof import('./utils/constant').NINETEEN_DIGITS
  const NUMBER: typeof import('./utils/constant').NUMBER
  const NUMBER_MAX: typeof import('./utils/constant').NUMBER_MAX
  const NUMBER_MIN: typeof import('./utils/constant').NUMBER_MIN
  const PASSWORD: typeof import('./utils/constant').PASSWORD
  const PagingDefaultConf: typeof import('./utils/constant').PagingDefaultConf
  const Protocol: typeof import('./utils/protocol').Protocol
  const SIX_NUMBER: typeof import('./utils/constant').SIX_NUMBER
  const THOUSANDS_REGULAR: typeof import('./utils/constant').THOUSANDS_REGULAR
  const VERSION_NUMBER_RULES: typeof import('./utils/constant').VERSION_NUMBER_RULES
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const addEventListener: typeof import('./utils/common').addEventListener
  const allToRaw: typeof import('./utils/allToRaw').default
  const buildFlat: typeof import('./utils/common').buildFlat
  const buildTableFetchResult: typeof import('./utils/table').buildTableFetchResult
  const buildTree: typeof import('./utils/common').buildTree
  const clearManageToken: typeof import('./utils/session').clearManageToken
  const colorArr: typeof import('./utils/constant').colorArr
  const computed: typeof import('vue').computed
  const copyToClipboard: typeof import('./utils/copyToClipboard').default
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const createTraceId: typeof import('./utils/session').createTraceId
  const customRef: typeof import('vue').customRef
  const debounceFunc: typeof import('./utils/common').debounceFunc
  const decodeHTMLEntities: typeof import('./utils/common').decodeHTMLEntities
  const decrypt: typeof import('./utils/aes_128_cbc').decrypt
  const decryptAESGCM: typeof import('./utils/aesGcm').decryptAESGCM
  const deepCopy: typeof import('./utils/common').deepCopy
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const encrypt: typeof import('./utils/aes_128_cbc').encrypt
  const encryptAESGCM: typeof import('./utils/aesGcm').encryptAESGCM
  const fetchTradeOptions: typeof import('./utils/tradeOptions').fetchTradeOptions
  const formatTaskState: typeof import('./utils/common').formatTaskState
  const formatText: typeof import('./utils/common').formatText
  const formatTradeOptionLabel: typeof import('./utils/tradeOptions').formatTradeOptionLabel
  const generateIv: typeof import('./utils/aes_128_cbc').generateIv
  const generateKey: typeof import('./utils/aes_128_cbc').generateKey
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getFlashLimitRangeText: typeof import('./utils/rangeText').getFlashLimitRangeText
  const getManageToken: typeof import('./utils/session').getManageToken
  const h: typeof import('vue').h
  const handlePaste: typeof import('./utils/common').handlePaste
  const hideMiddleText: typeof import('./utils/common').hideMiddleText
  const hyphenate: typeof import('./utils/common').hyphenate
  const inject: typeof import('vue').inject
  const isPromise: typeof import('./utils/common').isPromise
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const makeFilterItemKey: typeof import('./utils/common').makeFilterItemKey
  const makeFilterUnique: typeof import('./utils/common').makeFilterUnique
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const normalizeTableFetchResult: typeof import('./utils/table').normalizeTableFetchResult
  const numberSeparation: typeof import('./utils/common').numberSeparation
  const numberToChinese: typeof import('./utils/common').numberToChinese
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onCopyCode: typeof import('./utils/common').onCopyCode
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const permission: typeof import('./store/permission').default
  const protocol: typeof import('./utils/protocol').default
  const provide: typeof import('vue').provide
  const randomString: typeof import('./utils/common').randomString
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const recursionFind: typeof import('./utils/common').recursionFind
  const ref: typeof import('vue').ref
  const removeEventListener: typeof import('./utils/common').removeEventListener
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveLabelTagList: typeof import('./utils/labelTags').resolveLabelTagList
  const sanitizeTradeOptions: typeof import('./utils/tradeOptions').sanitizeTradeOptions
  const setActivePinia: typeof import('pinia').setActivePinia
  const setManageToken: typeof import('./utils/session').setManageToken
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const shuffleArray: typeof import('./utils/common').shuffleArray
  const sideBar: typeof import('./store/sideBar').default
  const sliceLength: typeof import('./utils/common').sliceLength
  const storeToRefs: typeof import('pinia').storeToRefs
  const tagsView: typeof import('./store/tagsView').default
  const theme: typeof import('./store/theme').default
  const throttleFunc: typeof import('./utils/common').throttleFunc
  const toCapital: typeof import('./utils/common').toCapital
  const toCountryAlpha3Options: typeof import('./utils/selectOptions').toCountryAlpha3Options
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toTagSelectOptions: typeof import('./utils/selectOptions').toTagSelectOptions
  const toValue: typeof import('vue').toValue
  const transMapBySelectOptions: typeof import('./utils/component').transMapBySelectOptions
  const triggerRef: typeof import('vue').triggerRef
  const typeOf: typeof import('./utils/common').typeOf
  const unknown: typeof import('./utils/table').unknown
  const unref: typeof import('vue').unref
  const unshiftSelectOptionAll: typeof import('./utils/component').unshiftSelectOptionAll
  const urlEncode: typeof import('./utils/common').urlEncode
  const useAttrs: typeof import('vue').useAttrs
  const useButtonRole: typeof import('./use/useButtonRole').default
  const useConfirmAction: typeof import('./use/useConfirmAction').default
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useCurrentUserSecurity: typeof import('./use/useCurrentUserSecurity').default
  const useDateLimit: typeof import('./use/useDateLimit').default
  const useFetchTableData: typeof import('./use/useFetchTableData').default
  const useFormHandler: typeof import('./use/useFormHandler').default
  const useGoogleTitle: typeof import('./use/useGoogleTitle').default
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useKeyDown: typeof import('./use/useKeyDown').default
  const useLink: typeof import('vue-router').useLink
  const useModalHandler: typeof import('./use/useModalHandler').default
  const useModel: typeof import('vue').useModel
  const useOnActivated: typeof import('./use/useOnActivated').useOnActivated
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTableSorter: typeof import('./use/useTableSorter').default
  const useTabsRole: typeof import('./use/useTabsRole').default
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useUpload: typeof import('./use/useUpload').default
  const useValidatorConf: typeof import('./use/useValidatorConf').default
  const user: typeof import('./store/user').default
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { LabelTagOption, LabelTagItem } from './utils/labelTags'
  import('./utils/labelTags')
  // @ts-ignore
  export type { ResponseType } from './use/useFetchTableData'
  import('./use/useFetchTableData')
}
