/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AOption: typeof import('@arco-design/web-vue')['Option']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    Approval: typeof import('./components/Approval.vue')['default']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATree: typeof import('@arco-design/web-vue')['Tree']
    AVerificationCode: typeof import('@arco-design/web-vue')['VerificationCode']
    BindGoogle: typeof import('./components/Modal/BindGoogle.vue')['default']
    CellEllipsis: typeof import('./components/TableSearchWrap/components/CellEllipsis.vue')['default']
    CodeInput: typeof import('./components/CodeInput.vue')['default']
    ColorPicker: typeof import('./components/ColorPicker.vue')['default']
    CopyableText: typeof import('./components/TableSearchWrap/components/CopyableText.vue')['default']
    Error: typeof import('./components/Error.vue')['default']
    ExportButton: typeof import('./components/TableSearchWrap/components/ExportButton.vue')['default']
    GoogleCode: typeof import('./components/GoogleCode.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    Index: typeof import('./components/TableSearchWrap/Index.vue')['default']
    Item: typeof import('./components/SideNavigationBar/Item.vue')['default']
    LabelTagList: typeof import('./components/TableSearchWrap/components/LabelTagList.vue')['default']
    ListApproval: typeof import('./components/ListApproval.vue')['default']
    NotRolePurview: typeof import('./components/NotRolePurview.vue')['default']
    PermissionButton: typeof import('./components/TableSearchWrap/components/PermissionButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings2FA: typeof import('./components/Settings2FA.vue')['default']
    SettingsPassword: typeof import('./components/SettingsPassword.vue')['default']
    SideNavigationBar: typeof import('./components/SideNavigationBar/index.vue')['default']
    StatusText: typeof import('./components/TableSearchWrap/components/StatusText.vue')['default']
    TagsView: typeof import('./components/TagsView.vue')['default']
    UserAuthCell: typeof import('./components/UserAuthCell.vue')['default']
  }
}
